simplified mount script and changed method of using mergerfs from daemon to using fstab

diff --git a/templates/rclone_mount b/templates/rclone_mount
--- a/templates/rclone_mount
+++ b/templates/rclone_mount
@@ -25,7 +25,7 @@ LocalFilesShare="_local_files_" # location of the local files and MountFolders y
 RcloneCacheShare="/mnt/user0/mount_rclone" # location of rclone cache files without trailing slash e.g. /mnt/user0/mount_rclone
 RcloneCacheMaxSize="_rclone_cache_max_" # Maximum size of rclone cache
 RcloneCacheMaxAge="336h" # Maximum age of cache files
-MergerfsMountShare="_merged_files_" # location without trailing slash  e.g. /mnt/user/mount_mergerfs. Enter 'ignore' to disable
+MergerfsMountShare="_merged_files_" # location without trailing slash  e.g. /mnt/user/mount_mergerfs. 
 DockerStart="_docker_apps_" # list of dockers, separated by space, to start once mergerfs mount verified. Remember to disable AUTOSTART for dockers added in docker settings page
 MountFolders=\{"downloads/complete,downloads/intermediate,downloads/seeds,movies,tv"\} # comma separated list of folders to create within the mount
 
@@ -77,12 +77,8 @@ else
 fi
 mkdir -p $RcloneMountLocation
 
-if [[  $MergerfsMountShare == 'ignore' ]]; then
-	echo "$(date "+%d.%m.%Y %T") INFO: Not creating MergerFS folders as requested."
-else
-	echo "$(date "+%d.%m.%Y %T") INFO: Creating MergerFS folders."
-	mkdir -p $MergerFSMountLocation
-fi
+echo "$(date "+%d.%m.%Y %T") INFO: Creating MergerFS folders."
+mkdir -p $MergerFSMountLocation
 
 
 #######  Check if script is already running  #######
@@ -169,73 +165,59 @@ else
 	fi
 fi
 
+
 ####### Start MergerFS Mount #######
 
-if [[  $MergerfsMountShare == 'ignore' ]]; then
-	echo "$(date "+%d.%m.%Y %T") INFO: Not creating mergerfs mount as requested."
+if [[ -f "$MergerFSMountLocation/mountcheck" ]]; then
+	echo "$(date "+%d.%m.%Y %T") INFO: Check successful, ${RcloneRemoteName} mergerfs mount in place."
 else
-	if [[ -f "$MergerFSMountLocation/mountcheck" ]]; then
-		echo "$(date "+%d.%m.%Y %T") INFO: Check successful, ${RcloneRemoteName} mergerfs mount in place."
-	else
 # check if mergerfs already installed
-		if [[ -f "/bin/mergerfs" ]]; then
-			echo "$(date "+%d.%m.%Y %T") INFO: Mergerfs already installed, proceeding to create mergerfs mount"
-		else
+	if [[ -f "/bin/mergerfs" ]]; then
+		echo "$(date "+%d.%m.%Y %T") INFO: Mergerfs already installed, proceeding to create mergerfs mount"
+	else
 # Build mergerfs binary
-			echo "$(date "+%d.%m.%Y %T") INFO: Mergerfs not installed - installing now."
-			mkdir -p /mnt/user/appdata/other/rclone/mergerfs
-			docker run -v /mnt/user/appdata/other/rclone/mergerfs:/build --rm trapexit/mergerfs-static-build
-			mv /mnt/user/appdata/other/rclone/mergerfs/mergerfs /bin
+		echo "$(date "+%d.%m.%Y %T") INFO: Mergerfs not installed - installing now."
+		mkdir -p /mnt/user/appdata/other/rclone/mergerfs
+		docker run -v /mnt/user/appdata/other/rclone/mergerfs:/build --rm trapexit/mergerfs-static-build
+		mv /mnt/user/appdata/other/rclone/mergerfs/mergerfs /bin
 # check if mergerfs install successful
-			echo "$(date "+%d.%m.%Y %T") INFO: *sleeping for 5 seconds"
-			sleep 5
-			if [[ -f "/bin/mergerfs" ]]; then
-				echo "$(date "+%d.%m.%Y %T") INFO: Mergerfs installed successfully, proceeding to create mergerfs mount."
-			else
-				echo "$(date "+%d.%m.%Y %T") ERROR: Mergerfs not installed successfully.  Please check for errors.  Exiting."
-				rm /mnt/user/appdata/other/rclone/remotes/$RcloneRemoteName/mount_running
-				exit
-			fi
-		fi
-# Create mergerfs mount
-		echo "$(date "+%d.%m.%Y %T") INFO: Creating ${RcloneRemoteName} mergerfs mount."
-# Extra Mergerfs folders
-		if [[  $LocalFilesShare2 != 'ignore' ]]; then
-			echo "$(date "+%d.%m.%Y %T") INFO: Adding ${LocalFilesShare2} to ${RcloneRemoteName} mergerfs mount."
-			LocalFilesShare2=":$LocalFilesShare2"
+		echo "$(date "+%d.%m.%Y %T") INFO: *sleeping for 5 seconds"
+		sleep 5
+		if [[ -f "/bin/mergerfs" ]]; then
+			echo "$(date "+%d.%m.%Y %T") INFO: Mergerfs installed successfully, proceeding to create mergerfs mount."
 		else
-			LocalFilesShare2=""
-		fi
-		if [[  $LocalFilesShare3 != 'ignore' ]]; then
-			echo "$(date "+%d.%m.%Y %T") INFO: Adding ${LocalFilesShare3} to ${RcloneRemoteName} mergerfs mount."
-			LocalFilesShare3=":$LocalFilesShare3"
-		else
-			LocalFilesShare3=""
-		fi
-		if [[  $LocalFilesShare4 != 'ignore' ]]; then
-			echo "$(date "+%d.%m.%Y %T") INFO: Adding ${LocalFilesShare4} to ${RcloneRemoteName} mergerfs mount."
-			LocalFilesShare4=":$LocalFilesShare4"
-		else
-			LocalFilesShare4=""
-		fi
-# make sure mergerfs mount point is empty
-		mv $MergerFSMountLocation $LocalFilesLocation
-		mkdir -p $MergerFSMountLocation
-
-# mergerfs mount command
-		mergerfs $LocalFilesLocation=RW:$RcloneMountLocation=RO $MergerFSMountLocation -o async_read=false,use_ino,allow_other,func.getattr=newest,category.action=all,category.create=ff,cache.files=partial,dropcacheonclose=true
-# check if mergerfs mount successful
-		echo "$(date "+%d.%m.%Y %T") INFO: Checking if ${RcloneRemoteName} mergerfs mount created."
-		if [[ -f "$MergerFSMountLocation/mountcheck" ]]; then
-			echo "$(date "+%d.%m.%Y %T") INFO: Check successful, ${RcloneRemoteName} mergerfs mount created."
-		else
-			echo "$(date "+%d.%m.%Y %T") CRITICAL: ${RcloneRemoteName} mergerfs mount failed.  Stopping dockers."
-			docker stop $DockerStart
+			echo "$(date "+%d.%m.%Y %T") ERROR: Mergerfs not installed successfully.  Please check for errors.  Exiting."
 			rm /mnt/user/appdata/other/rclone/remotes/$RcloneRemoteName/mount_running
 			exit
 		fi
 	fi
+# Create mergerfs mount
+	echo "$(date "+%d.%m.%Y %T") INFO: Creating ${RcloneRemoteName} mergerfs mount."
+
+# make sure mergerfs mount point is empty
+	mv $MergerFSMountLocation $LocalFilesLocation
+	mkdir -p $MergerFSMountLocation
+
+# add the mergerfs mount to fstab if it is not already there
+	if ! grep -q 'init-mergermount' /etc/fstab; 
+	then 
+		printf "# init-mergermount\n${LocalFilesLocation}=RW:${RcloneMountLocation}=RO ${MergerFSMountLocation} fuse.mergerfs async_read=false,use_ino,allow_other,func.getattr=newest,category.action=all,category.create=ff,cache.files=partial,dropcacheonclose=true 0 0\n" >> /etc/fstab
+		systemctl daemon-reload
+		mount -a
+	fi
+
+# check if mergerfs mount successful
+	echo "$(date "+%d.%m.%Y %T") INFO: Checking if ${RcloneRemoteName} mergerfs mount created."
+	if [[ -f "$MergerFSMountLocation/mountcheck" ]]; then
+		echo "$(date "+%d.%m.%Y %T") INFO: Check successful, ${RcloneRemoteName} mergerfs mount created."
+	else
+		echo "$(date "+%d.%m.%Y %T") CRITICAL: ${RcloneRemoteName} mergerfs mount failed.  Stopping dockers."
+		docker stop $DockerStart
+		rm /mnt/user/appdata/other/rclone/remotes/$RcloneRemoteName/mount_running
+		exit
+	fi
 fi
+
 
 ####### Starting Dockers That Need Mergerfs Mount To Work Properly #######
 
